export const FETCH_PODCASTS_PENDING:string = 'FETCH_PODCASTS_PENDING';
export const FETCH_PODCASTS_SUCCESS:string = 'FETCH_PODCASTS_SUCCESS';
export const FETCH_PODCASTS_ERROR:string = 'FETCH_PODCASTS_ERROR'